### ISSUE TITLE
Stop Thief!

### ISSUE THREAD

**Issue by pvrs12** [hucario/genericplayer#1]
https://youtu.be/SplJ7U0Jgtw

jkjk, do you want pull access to Anesidora? I can't as easily give you access to update the extension within Firefox (rip chrome), but I can certainly give you access to update the github

**Comment by hucario** [comment]
Eh, at this point it's become a whole separate thing. It's on me for not updating the readme with screenshots, so uh here's a few videos I posted to Discord:
(By the way, these were posted as progress updates: Features incomplete in prior videos may be completed in later ones)

Navigation, station and accordion mockup components, using sample data:
https://cdn.discordapp.com/attachments/734115770488848414/815072182006448178/2021-02-26_19-57-49.mp4
Update where I made accordion components actually function (search pulls from iTunes at this point):
https://cdn.discordapp.com/attachments/734115770488848414/819003617742553145/2021-03-09_16-25-45.mp4
Search functionality, album pages (including album not found pages), pulls from Pandora now:
https://cdn.discordapp.com/attachments/734115770488848414/824076732092252160/2021-03-23_17-24-25.mp4
Default image for when there's no image associated with an album / artist:
https://cdn.discordapp.com/attachments/734115770488848414/825444053008121926/2021-03-27_11-59-15.mp4
(has sound from a different tab; I was just listening to that while working, it's _not_ from the player)
Artist version:
![image](https://user-images.githubusercontent.com/50851047/115437671-51ea4600-a1c1-11eb-82af-158dcecab512.png)
Quickbuttons: (non functional, just mockups still)
https://cdn.discordapp.com/attachments/734115770488848414/825504031237603328/2021-03-27_15-55-07.mp4
Requests now cache (quick and dirty; an object using the fetch `options` parameter as the key :LUL:)
https://cdn.discordapp.com/attachments/734115770488848414/825592596587872296/2021-03-27_21-49-22.mp4
Cached searches (example debounce at 5s to make it clear what's cached and what's not):
https://cdn.discordapp.com/attachments/734115770488848414/825597767036567582/2021-03-27_22-09-58.mp4
Trending page (pulls from Pandora):
https://cdn.discordapp.com/attachments/734115770488848414/830290378006724688/2021-04-09_20-55-26.mp4


I'll get more screenshots when I get home I'm just not on my PC with genericplayer on it currently.
The github is close-ish to latest (look I keep forgetting to commit and push) so it'll get you a close preview of latest.

anyways I was saying something

oh right yeah GenericPlayer is kind of a big project now and I don't feel that it fits with Anesidora
I'll patch the horrendous mistakes I made in Anesidora (the drop-shadow hack 🅰️), but it's not just Anesidora anymore.
Pull access to Anesidora is fine, but again I'll ask you before I make any pulls anyways so it's not that big of a deal to me whether I have it or not

**Comment by hucario** [comment]
Uploading 2021-04-22 19-20-46.mp4…

**Comment by hucario** [comment]
https://user-images.githubusercontent.com/50851047/115811112-fb892d00-a3a3-11eb-8182-b383041ab08a.mp4

**Comment by pvrs12** [comment]
Yo, that looks so sick. Is this still based on the Pandora API? That’s super impressive. I am also a big fan of the web UI which _isn’t_ electron (I am so biased).

________________________________

**Comment by hucario** [comment]
> Yo, that looks so sick. Is this still based on the Pandora API?

yep, it's still based on the pandora API

> web UI which _isn’t_ electron

you're going to be disappointed then because yes it's react (assuming that you meant to say react; electron is for web -> ""native"" ports, it's not a web framework)

the problem is that with a project of this scale you're going to want a framework or else the codebase gets _large_[0]
I mean I _could_ do it without React but it would be a _massive_ pain
especially the navigation
and avoiding innerHTML[1]

if you actually _were_ talking about avoiding electron that's possible with React Native although I don't know why you'd want to go native (but yes if I were to I would avoid Electron as much as possible)



<details>
    <summary>fruit by the footnotes</summary>

[0] "but isn't it already large with the dependencies?"
yes but you know I mean the _visible_ code that the developer actively works on instead of just shoving it in node_modules

[1] with react you can use jsx:
instead of having to write 
```js
let parent = document.createElement('div'); 
document.body.appendChild(parent);
let child = document.createElement('span');
parent.appendChild(child);
child.innerText="yeah";
```
you can just write
```jsx
return (<div>
    <span>yeah</span>
</div>)
```

plus, managing state becomes far less of a pain
I get it's a large framework but _still_ I think it's worth it

</details>
